---
# Setup/install tasks.

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install mycli via pip.
  pip: "name=mycli version={{ mycli_version }}"
  become: yes
